//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OneDuyKhanhDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class May
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public May()
        {
            this.BoGiamSats = new HashSet<BoGiamSat>();
            this.CongViecs = new HashSet<CongViec>();
            this.LichSuMays = new HashSet<LichSuMay>();
            this.SuaChuas = new HashSet<SuaChua>();
            this.ThoiGianMays = new HashSet<ThoiGianMay>();
            this.TinhTrangMays = new HashSet<TinhTrangMay>();
        }
    
        public int Id { get; set; }
        public string MaSo { get; set; }
        public string Ten { get; set; }
        public bool ThanhLy { get; set; }
        public string GhiChu { get; set; }
        public byte[] RowVersion { get; set; }
        public Nullable<int> May_ToSX { get; set; }
        public string NhanHieu { get; set; }
        public string Model { get; set; }
        public string NamSX { get; set; }
        public Nullable<System.DateTime> NgayBD_VH { get; set; }
        public Nullable<double> DonGia { get; set; }
        public string UuNhuocDiem { get; set; }
        public Nullable<bool> DangSua { get; set; }
        public string ThongSoKT { get; set; }
        public Nullable<double> Inactive { get; set; }
        public Nullable<double> Standby { get; set; }
        public Nullable<double> Inactivetest { get; set; }
        public Nullable<double> Standbytest { get; set; }
        public Nullable<int> LichHoatDongMay_May { get; set; }
        public Nullable<System.DateTime> KHKTHT { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BoGiamSat> BoGiamSats { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CongViec> CongViecs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LichSuMay> LichSuMays { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SuaChua> SuaChuas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ThoiGianMay> ThoiGianMays { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TinhTrangMay> TinhTrangMays { get; set; }
    }
}
