//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OneDuyKhanhDataAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class OneDuyKhanh4Entities : DbContext
    {
        public OneDuyKhanh4Entities()
            : base("name=OneDuyKhanh4Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BoGiamSat> BoGiamSats { get; set; }
        public virtual DbSet<CongViec> CongViecs { get; set; }
        public virtual DbSet<LichSuMay> LichSuMays { get; set; }
        public virtual DbSet<May> Mays { get; set; }
        public virtual DbSet<NhanVien> NhanViens { get; set; }
        public virtual DbSet<SuaChua> SuaChuas { get; set; }
        public virtual DbSet<ThoiGianMay> ThoiGianMays { get; set; }
        public virtual DbSet<TinhTrangMay> TinhTrangMays { get; set; }
    }
}
