//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OneDuyKhanhDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class SuaChua
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> NgayYeuCau { get; set; }
        public Nullable<System.DateTime> NgayYCHT { get; set; }
        public Nullable<int> May { get; set; }
        public Nullable<int> NguoiYeuCau { get; set; }
        public string NoiDungHong { get; set; }
        public Nullable<System.DateTime> NgayNhan { get; set; }
        public Nullable<int> NguoiSua { get; set; }
        public Nullable<System.DateTime> NgayHoanThanh { get; set; }
        public Nullable<System.DateTime> NgayNghiemThu { get; set; }
        public string TenThietBi { get; set; }
        public Nullable<int> NguoiNhanBanGiao { get; set; }
        public Nullable<bool> NhanSuaMay { get; set; }
        public Nullable<bool> HoanThanh { get; set; }
        public Nullable<bool> NghiemThu { get; set; }
    
        public virtual May May1 { get; set; }
    }
}
