//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OneDuyKhanhDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class TinhTrangMay
    {
        public int Id { get; set; }
        public Nullable<int> boGiamSat { get; set; }
        public Nullable<int> may { get; set; }
        public Nullable<int> trangThai { get; set; }
        public Nullable<double> CongSuat { get; set; }
        public Nullable<System.DateTime> ThoiGianCapNhatCuoiCung { get; set; }
        public byte[] HinhAnh { get; set; }
        public Nullable<int> thoigianMay { get; set; }
    
        public virtual BoGiamSat BoGiamSat1 { get; set; }
        public virtual May May1 { get; set; }
        public virtual ThoiGianMay ThoiGianMay1 { get; set; }
    }
}
