//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OneDuyKhanhDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class LichSuMay
    {
        public int Id { get; set; }
        public Nullable<int> GiamSatMay { get; set; }
        public Nullable<System.DateTime> ThoiGianCapNhat { get; set; }
        public Nullable<double> CongSuatPhaA { get; set; }
        public Nullable<double> CongSuatPhaB { get; set; }
        public Nullable<double> CongSuatPhaC { get; set; }
        public Nullable<double> DongDienPhaA { get; set; }
        public Nullable<double> DongDienPhaB { get; set; }
        public Nullable<double> DongDienPhaC { get; set; }
        public Nullable<double> DienApPhaA { get; set; }
        public Nullable<double> DienApPhaB { get; set; }
        public Nullable<double> DienApPhaC { get; set; }
        public Nullable<int> trangThai { get; set; }
    
        public virtual May May { get; set; }
    }
}
