//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OneDuyKhanhDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThoiGianMay_Thang
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> NgayCapNhat { get; set; }
        public Nullable<int> may { get; set; }
        public Nullable<int> boGiamSat { get; set; }
        public Nullable<int> RunningTime { get; set; }
        public Nullable<int> WaitTime { get; set; }
        public Nullable<int> RunErrTime { get; set; }
        public Nullable<int> SetUpTime { get; set; }
        public Nullable<int> OffTime { get; set; }
        public Nullable<double> congsuat { get; set; }
        public Nullable<double> NangLuong { get; set; }
    
        public virtual May May1 { get; set; }
    }
}
